spring.application.name=clasedominio
server.port=8080

spring.thymeleaf.cache=false

spring.datasource.url=jdbc:postgresql://localhost:5432/individuos
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=admin

